[package]
name = "rustmath-reals"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
rustmath-core = { path = "../rustmath-core" }
rustmath-integers = { path = "../rustmath-integers" }
rustmath-rationals = { path = "../rustmath-rationals" }
num-traits = { workspace = true }
serde = { workspace = true, optional = true }
rug = { version = "1.24", default-features = false, features = ["float", "integer"] }

[features]
default = []
serde = ["dep:serde"]
