[package]
name = "rustmath-sets"
version = "0.1.0"
edition = "2021"

[dependencies]
rustmath-core = { path = "../rustmath-core" }
rustmath-integers = { path = "../rustmath-integers" }
rustmath-rationals = { path = "../rustmath-rationals" }
