[package]
name = "rustmath-stats"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
rustmath-core = { path = "../rustmath-core" }
rustmath-reals = { path = "../rustmath-reals" }
rustmath-rationals = { path = "../rustmath-rationals" }
rand = { workspace = true }
