[package]
name = "rustmath-monoids"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4"
num-rational = "0.4"
num-traits = "0.2"
num-integer = "0.1"
rustmath-core = { path = "../rustmath-core" }
rustmath-integers = { path = "../rustmath-integers" }

[dev-dependencies]
