[package]
name = "rustmath-symmetricfunctions"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
rustmath-core = { path = "../rustmath-core" }
rustmath-integers = { path = "../rustmath-integers" }
rustmath-rationals = { path = "../rustmath-rationals" }
rustmath-combinatorics = { path = "../rustmath-combinatorics" }
rustmath-matrix = { path = "../rustmath-matrix" }
num-bigint.workspace = true
num-rational.workspace = true
num-traits.workspace = true

[dev-dependencies]
