[package]
name = "rustmath-modules"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
rustmath-core = { path = "../rustmath-core" }
rustmath-category = { path = "../rustmath-category" }
rustmath-integers = { path = "../rustmath-integers" }
rustmath-rationals = { path = "../rustmath-rationals" }
rustmath-matrix = { path = "../rustmath-matrix" }
rustmath-polynomials = { path = "../rustmath-polynomials" }
rustmath-finitefields = { path = "../rustmath-finitefields" }
num-bigint = { workspace = true }
num-rational = { workspace = true }
num-traits = { workspace = true }
num-integer = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
